In [63]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
class color:
    PURPLE = '\033[95m'
    CYAN = '\033[96m'
    DARKCYAN = '\033[36m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    END = '\033[0m'
pd.set_option("display.max_columns", 180)
from tqdm.notebook import tqdm
from pathlib import Path
from IPython.display import display

In [49]:
def normalize(data):
    df=data.copy()
    for column in df.columns[11:]:
        minim = df[column].min()
        maxim = df[column].max()
        df[column] = (df[column] - minim) / (maxim - minim)
    return df

In [50]:
def compute_similarity(data, player, min_minutes=100):
    df = data[data.minutesPlayed>=min_minutes].reset_index(drop=True)
    df = normalize(df)
    j = df[df['playerId']==player].index.values[0]    
    similarity = df.copy()
    for row in range(0,len(df)):
        for column in df.columns[11:]:
            similarity.at[row,column] = abs(df.loc[row,column] - df.loc[j,column])
            
    similarity['Distance']= similarity.iloc[:,11:].mean(axis=1) 
    similarity['SimilarityIndex'] = round((1 - similarity['Distance'])*100, 3)
    similarity = similarity[['playerId', 
                             'shortName', 
                             'team', 
                             'position', 
                             'age',
                             'height', 
                             'foot', 
                             'minutesPlayed',
                             'marketValue', 
                             'goals', 
                             'minutesPlayed', 
                             'SimilarityIndex']]
    similarity = similarity.sort_values(by='SimilarityIndex', ascending=False).iloc[1:,:].reset_index(drop=True)
    return similarity

In [51]:
PATH = Path('C:/Users/gmanf/OneDrive/Documents/GitHub/Published-Studies/Playing Style Soccer/data/')

In [52]:
df = pd.read_csv(PATH / 'full_data.csv', delimiter=',')

In [53]:
df.head(3)

,playerId,shortName,team,position,height,foot,age,value,marketValue,minutesPlayed,goals,X_pass_mean,X_pass_std,Y_pass_mean,Y_pass_std,forward_passes,smart_passes,pass_end_z1,pass_end_z2,pass_end_z3,pass_end_z4,pass_end_z5,pass_end_z6,pass_end_z7,pass_end_z8,pass_end_z9,pass_reception_z1,pass_reception_z2,pass_reception_z3,pass_reception_z4,pass_reception_z5,pass_reception_z6,pass_reception_z7,pass_reception_z8,pass_reception_z9,dribble_z1,dribble_z2,dribble_z3,dribble_z4,dribble_z5,dribble_z6,dribble_z7,dribble_z8,dribble_z9,cross_z1,cross_z2,cross_z3,cross_z4,shot_z1,shot_z2,shot_z3,shot_z4,shot_wleft,shot_wright,shot_whead,defense_z1,defense_z2,defense_z3,defense_z4,defense_z5,defense_z6,defense_z7,defense_z8,defense_z9,defense_z10,defense_z11,defense_z12,clearances_per90,interceptions_per90,tackles_per90,loose_ball_won_per90,final_third_recovery_per90,air_success,headers_per90,ABCD,BACD,BCAD,BCDA,ABAB,BABA,ABAC,BABC,BCBA,ABCA,BACB,BCAB,ABCB,BACA,BCAC,flow_centrality
0,36,T. Alderweireld,Tottenham Hotspur,Defender,187,right,29,40000000,"$40,000,000",1170,0,8.029719,10.417564,14.853012,16.693716,0.641425,0.001266,0.097468,0.220253,0.178481,0.093671,0.097468,0.188608,0.026582,0.008861,0.050633,0.033183,0.245852,0.423831,0.028658,0.051282,0.191554,0.001508,0.009050,0.015083,0.000000,0.000000,0.192308,0.000000,0.0,0.192308,0.000000,0.000000,0.000000,0.076923,0.538462,0.000000,0.000000,0.461538,0.153846,0.153846,0.000000,0.100000,0.700000,0.200000,0.090000,0.090000,0.210000,0.060000,0.040000,0.330000,0.020000,0.000000,0.110000,0.020000,0.000000,0.030000,2.307692,4.153846,1.307692,1.000000,0.384615,0.418182,5.846154,22.538462,24.000000,23.923077,18.769231,0.615385,0.769231,6.000000,3.538462,5.923077,2.769231,3.153846,2.461538,5.384615,5.846154,3.307692,0.474259
1,48,J. Vertonghen,Tottenham Hotspur,Defender,189,left,31,32000000,"$32,000,000",3204,0,6.964338,9.240700,12.774241,14.627903,0.629114,0.001420,0.186465,0.247989,0.072409,0.247042,0.101751,0.053478,0.030762,0.010412,0.011358,0.468848,0.195721,0.003776,0.237885,0.074890,0.000000,0.014475,0.004405,0.000000,0.216693,0.108347,0.000000,0.072231,0.0,0.000000,0.072231,0.000000,0.036116,0.365169,0.000000,0.140449,0.000000,0.393258,0.196629,0.028090,0.028090,0.652174,0.173913,0.173913,0.180556,0.086806,0.048611,0.319444,0.072917,0.031250,0.152778,0.065972,0.006944,0.017361,0.010417,0.006944,2.387640,5.926966,1.994382,1.601124,0.646067,0.643192,8.314607,22.275281,21.882022,21.713483,16.544944,0.674157,0.533708,5.028090,3.904494,5.421348,2.640449,1.938202,1.994382,5.140449,4.550562,3.539326,0.480532
2,54,C. Eriksen,Tottenham Hotspur,Midfielder,180,right,26,80000000,"$80,000,000",3226,10,5.383509,7.939523,9.210094,13.217376,0.420765,0.023295,0.064337,0.088186,0.089850,0.161952,0.178037,0.156961,0.073211,0.049917,0.091514,0.059779,0.077191,0.094602,0.165409,0.282647,0.188044,0.038305,0.030760,0.063262,0.065096,0.000000,0.130192,0.260384,0.0,0.130192,0.195288,0.130192,0.000000,0.725356,1.590205,0.278983,0.474272,1.394916,0.278983,0.334780,0.223187,0.337500,0.650000,0.012500,0.040741,0.014815,0.033333,0.118519,0.066667,0.107407,0.122222,0.125926,0.177778,0.048148,0.055556,0.088889,0.390577,3.013019,0.809051,1.255425,2.064476,0.288462,3.626782,14.730316,16.236826,17.715437,18.719777,0.669560,0.976441,4.128952,4.352139,3.822071,3.654681,2.259764,3.013019,3.738376,4.575325,4.770614,0.464146

## Simple program that allows to search Top N most similar players to a reference player

In [66]:
i=0
while i<1:
    j=0
    while j<1:
        player_string = input('\n Search for player: ')
        search = df[(df['shortName'].str.contains(player_string, case=False))][['playerId','shortName', 'team', 'position', 'marketValue']]
        if search.shape[0]==0:
            print('\n No results found. Please try again. Do not include the first name of the player, but only his last name or nickname.')
            j=j
        else:
            j=j+1
    display(search)
    playerId = input('\n Enter the playerId of the player you were looking for, or enter 0 for a new search: ')
    try:
        playerId = int(playerId)
    except:
        playerId = input('\n Please enter an integer number (playerId): ')
        playerId = int(playerId)
    if playerId==0:
        i=i
    else:
            i=i+1
value = input("\n Look for similar players for less than (in millions of euros, type 'Any' if no money filter is desired): ")
if (value!='Any') and (value!='any'):
    try:
        value = float(value)
        value = value*1000000
    except:
        value = input('\n Please enter a number (market value in millions of Euros): ')
        value = float(value)
        value = value*1000000
        
if df[df['playerId']==playerId]['playerId'].any():
    print('\nComputing Similarity. Please wait...')
    df=normalize(df)
    similarity = compute_similarity(df,playerId,900)
    print(color.BOLD + "\nThe 5 players most similar to {} for less than {} Euros are:".format(
                                                        df[df['playerId']==playerId]['shortName'].iloc[0], value) + color.END)
    if (value!='Any') and (value!='any'):
        similarity = similarity[similarity['value']<=value]
        aux = similarity.reset_index()
        num = aux.iloc[0,aux.columns.get_loc('index')]
        print('(Note: There are {} players more similar to {} than {} for a higher price)'.format(
                                    num, all_players[all_players['playerId']==playerId]['shortName'].iloc[0], aux.iloc[0,2]))
    show = similarity[['playerId', 'shortName', 'team', 'position', 'age','height', 'foot', 'marketValue', 'goals', 'minutesPlayed', 'SimilarityIndex']].reset_index(drop=True)
    display(show.head(5))
else:
    print('\nPlayer does not exist or did not play the minimum 900 minutes across the 2017-18 season. \n\
    Please try a different player.')

 Search for player: messi

    playerId shortName       team position     marketValue
91      3359  L. Messi  Barcelona  Forward   $180,000,000

 Enter the playerId of the player you were looking for, or enter 0 for a new search: 3359

 Look for similar players for less than (in millions of euros, type 'Any' if no money filter is desired): any

Computing Similarity. Please wait...

The 5 players most similar to L. Messi for less than any Euros are:

,playerId,shortName,team,position,age,height,foot,marketValue,goals,minutesPlayed,minutesPlayed,SimilarityIndex
0,89186,P. Dybala,Juventus,Forward,24,177,left,"$110,000,000",16,2359,2359,88.298
1,25707,E. Hazard,Chelsea,Forward,27,173,right,"$110,000,000",10,2432,2432,86.228
2,20820,J. Ilicic,Atalanta,Forward,30,190,left,"$13,000,000",9,2002,2002,85.554
3,3840,Iago Aspas,Celta de Vigo,Forward,31,176,left,"$25,000,000",19,2927,2927,85.279
4,28115,N. Fekir,Olympique Lyonnais,Midfielder,25,173,left,"$60,000,000",12,2482,2482,85.199